name: bmr
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  #universal
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_cache_manager: ^3.3.1
  go_router: ^13.0.0
  shared_preferences: ^2.0.15
  intl: ^0.20.2

  #network
  connectivity_plus: ^5.0.2
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-

  #ui
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  gap: ^3.0.1
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  another_flushbar: ^1.12.30



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/

